:toc:
:toc-placement: manual
:toc-title: 
:toclevels: 4

[preface]
== Table of contents
toc::[]

== Application Compatibility Cache Key
[yellow-background]*TODO add some description*

[NOTE]
Several sources claim that the Application Compatibility Cache is part of the
https://msdn.microsoft.com/en-us/library/bb432182(v=vs.85).aspx[Application Compatibility Database].
However these claims are not backed by facts. This document therefore
assumes the Application Compatibility Cache part of the Windows Application
Compatibility subsystem not the database.

The Application Compatibility Cache (or Shim Cache) seems to have been 
introduced in (at least) Windows XP. The format is significantly different 
between the different versions of Windows.

The Application Compatibility Cache can be found in the Registry key:

In Windows 2000 and XP:
....
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\AppCompatibility
....

In Windows 2003 and later:
....
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\AppCompatCache
....

=== Windows 2000
Windows 2000 stores Application Compatibility related data in subkeys in:
....
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\AppCompatibility
....

At this time it is unclear if these subkeys serve the same purpose as the 
AppCompatCache value in later versions of Windows.

The subkeys are named as the executable files e.g. `Uninstall.exe` and have been
seen to contain the following values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| %NAME% | | [yellow-background]*Unknown* +
[yellow-background]*Names seen: x, 462
| DllPatch-%NAME% | | [yellow-background]*Unknown*
|===

Also seen values named like `00008 WindowsNT4.0`.

==== Windows 2000 unknown value
The Windows 2000 unknown value is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 0x0000000c | [yellow-background]*Unknown 1 (header size?)*
| 4 | 4 | | [yellow-background]*Unknown 2 (empty values)*
| 8 | 4 | | [yellow-background]*Unknown 3*
| 12 | 4 | | [yellow-background]*Unknown 4*
4+| _If Unknown 4 > 0_
|===

....
Empty?
00000000  0c 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00  |................|

With data:
00000000  0c 00 00 00 00 00 00 00  06 00 00 00 04 00 00 00  |................|

00000010  10 00 00 00 00 00 00 00  00 00 15 00 ff ff ff ff  |................|
00000020  ff ff ff ff 0f 00 00 00                           |........(...A.u.|

Sting byte size followed by string:
00000020                           28 00 00 00 41 00 75 00  |........(...A.u.|
00000030  74 00 6f 00 43 00 41 00  44 00 20 00 41 00 70 00  |t.o.C.A.D. .A.p.|
00000040  70 00 6c 00 69 00 63 00  61 00 74 00 69 00 6f 00  |p.l.i.c.a.t.i.o.|
00000050  6e 00 00 00                                       |n.......|

00000050              00 00 00 00                           |n.......|
....

==== Windows 2000 DllPatch value
The Windows 2000 DllPatch value is variable of size and contains an UTF-16 
little-endian formatted string with end-of-string character e.g. `shcmn.dll 7`.

[yellow-background]*It is currently unclear what the trailing number represents.*

=== Windows XP
Windows XP stores the application compatibility cache in the value: AppCompatCache.

The value data consists of:

* header
* array of cache entries (suggested that the maximum is 92)

[NOTE]
64-bit versions of Windows XP will use the Windows 2003 64-bit format.

==== Windows XP application compat cache header
The Windows XP application compat cache header is 400 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 0xef, 0xbe, 0xad, 0xde | Signature
| 4 | 4 | | Number of cached entries
| 8 | 4 | | [yellow-background]*Unknown (number of header array entries?)*
| 12 | 4 | 0x00000000 | Unknown, empty values
| 16 | ... | | Array of 32-bit values
| ... | ... | | [yellow-background]*Unknown (padding?)* +
Contains 0-byte values
|===

==== Windows XP 32-bit application compat cache entry
The Windows XP 32-bit application compat cache entry is 552 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 x ( MAX_PATH + 4 ) = 528 | | Path +
UTF-16 little-endian string with end-of-character +
Note that the unused bytes can contain remnant data
| 528 | 8 | | Last modification time +
Contains a FILETIME
| 536 | 8 | | File size
| 544 | 8 | | Last update time +
Contains a FILETIME
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

=== Windows 2003
Windows 2003 stores the application compatibility cache in the value: AppCompatCache

The value data consists of:

* header
* array of cache entries (suggested that the maximum is 512)
* string data

==== Windows 2003 application compat cache header
The Windows 2003 application compat cache header is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 0xfe, 0x0f, 0xdc, 0xba | Signature
| 4 | 4 | | Number of cached entries
|===

==== Windows 2003 32-bit application compat cache entry
The Windows 2003 32-bit application compat cache entry is 24 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Path size
| 2 | 2 | | Maximum path size
| 4 | 4 | | Path offset +
The offset value is relative to the start of the header
| 8 | 8 | | Last modification time +
Contains a FILETIME
| 16 | 8 | | File size
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

==== Windows 2003 64-bit application compat cache entry
The Windows 2003 64-bit application compat cache entry is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Path size
| 2 | 2 | | Maximum path size
| 4 | 4 | | [yellow-background]*Unknown (padding)*
| 8 | 8 | | Path offset +
The offset value is relative to the start of the header
| 16 | 8 | | Last modification time +
Contains a FILETIME
| 24 | 8 | | File size
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

=== Windows Vista and 2008
Windows Vista and 2008 store the application compatibility cache in the value: AppCompatCache

The value data consists of:

* header
* array of cache entries (suggested that the maximum is 1024)
* string data

[NOTE]
If the cache is empty it will only consists of a header.
 
==== Windows Vista application compat cache header
The Windows Vista application compat cache header is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 0xfe, 0x0f, 0xdc, 0xba | Signature
| 4 | 4 | | Number of cached entries
|===

==== Windows Vista 32-bit application compat cache entry
The Windows Vista 32-bit application compat cache entry is 24 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Path size
| 2 | 2 | | Maximum path size
| 4 | 4 | | Path offset +
The offset value is relative to the start of the header
| 8 | 8 | | Last modification time +
Contains a FILETIME
| 16 | 4 | | Insertion flags
| 20 | 4 | | Shim flags
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

==== Windows Vista 64-bit application compat cache entry
The Windows Vista 64-bit application compat cache entry is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Path size
| 2 | 2 | | Maximum path size
| 4 | 4 | | [yellow-background]*Unknown (padding)*
| 8 | 8 | | Path offset +
The offset value is relative to the start of the header
| 16 | 8 | | Last modification time +
Contains a FILETIME
| 16 | 4 | | Insertion flags
| 20 | 4 | | Shim flags
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

=== Windows 7 and 2008 R2
Windows 7 and 2008 R2 store the application compatibility cache in the value: AppCompatCache

The value data consists of:

* header
* array of cache entries (suggested that the maximum is 1024)
* data
* string data

==== Windows 7 application compat cache header
The Windows 7 application compat cache header is 128 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 0xee, 0x0f, 0xdc, 0xba | Signature
| 4 | 4 | | Number of cached entries
| 8 | 120 | | [yellow-background]*Unknown (cache statistics?)*
|===

==== Windows 7 32-bit application compat cache entry
The Windows 7 32-bit application compat cache entry is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Path size +
The byte of the path without the end-of-string character
| 2 | 2 | | Maximum path size +
The byte of the path with the end-of-string character
| 4 | 4 | | Path offset +
The offset value is relative to the start of the header
| 8 | 8 | | Last modification time +
Contains a FILETIME
| 16 | 4 | | Insertion flags
| 20 | 4 | | Shim flags
| 24 | 4 | | Data size
| 28 | 4 | | Data offset +
The offset value is relative to the start of the header
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

==== Windows 7 64-bit application compat cache entry
The Windows 7 64-bit application compat cache entry is 48 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Path size +
The byte of the path without the end-of-string character
| 2 | 2 | | Maximum path size +
The byte of the path with the end-of-string character
| 4 | 4 | | [yellow-background]*Unknown (padding)*
| 8 | 8 | | Path offset +
The offset value is relative to the start of the header
| 16 | 8 | | Last modification time +
Contains a FILETIME
| 24 | 4 | | Insertion flags
| 28 | 4 | | Shim flags
| 32 | 8 | | Data size
| 40 | 8 | | Data offset +
The offset value is relative to the start of the header
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

=== Windows 8
Windows 8 store the application compatibility cache in the value: AppCompatCache

The value data consists of:

* header
* array of cache entries

==== Windows 8 application compat cache header
The Windows 8 application compat cache header is 128 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 128 | Header size (or cache entry array offset)
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 120 | | [yellow-background]*Unknown*
|===

==== Windows 8.0 application compat cache entry
The Windows 8.0 application compat cache entry is variable bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "00ts" | Signature
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | Cache entry data size +
The size of the cache entry without the first 12 bytes
| 12 | 2 | | Path size
| 14 | ... | | Path +
UTF-16 little-endian string without end-of-character
| ... | 4 | | [yellow-background]*Unknown (Insertion flags?)*
| ... | 4 | | [yellow-background]*Unknown (Shim flags?)*
| ... | 8 | | Last modification time +
Contains a FILETIME
| ... | 4 | | Data size
| ... | ... | | Data
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

==== Windows 8.1 application compat cache entry
The Windows 8.1 application compat cache entry is variable bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "10ts" | Signature
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | Cache entry data size +
The size of the cache entry without the first 12 bytes
| 12 | 2 | | Path size
| 14 | ... | | Path +
UTF-16 little-endian string without end-of-character
| ... | 4 | | [yellow-background]*Unknown (Insertion flags?)*
| ... | 4 | | [yellow-background]*Unknown (Shim flags?)*
| ... | 2 | | [yellow-background]*Unknown*
| ... | 8 | | Last modification time +
Contains a FILETIME
| ... | 4 | | Data size
| ... | ... | | Data
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

=== Windows 10
Windows 10 store the application compatibility cache in the value: AppCompatCache

The value data consists of:

* header
* array of cache entries

==== Windows 10 application compat cache header
The Windows 10 application compat cache header is 48 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 48 | Header size (or cache entry array offset)
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | [yellow-background]*Unknown (empty values)*
| 12 | 4 | | [yellow-background]*Unknown*
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 16 | | [yellow-background]*Unknown (empty values)*
| 36 | 4 | | Number of cached entries
| 40 | 8 | | [yellow-background]*Unknown (empty values)*
|===

==== Windows 10 application compat cache entry
The Windows 10 application compat cache entry is variable bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "10ts" | Signature
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | Cache entry data size +
The size of the cache entry without the first 12 bytes
| 12 | 2 | | Path size
| 14 | ... | | Path +
UTF-16 little-endian string without end-of-character
| ... | 8 | | Last modification time +
Contains a FILETIME
| ... | 4 | | Data size
| ... | ... | | Data
|===

[NOTE]
The last modification time applies to that of the file e.g. for NTFS this is 
the last modified time of the file as stored in the $STANDARD_INFORMATION 
attribute.

=== Insertion flags
[yellow-background]*TODO describe*

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | |
| 0x00000002 | |
| 0x00000004 | |
| 0x00000008 | |
|===

=== Shim flags
[yellow-background]*TODO describe*

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | | [yellow-background]*Unknown (Has data?)*
| 0x00000020 | |
| 0x00000100 | |
| 0x00001000 | |
|===

=== Data
[yellow-background]*TODO describe*

== External Links
* https://dl.mandiant.com/EE/library/Whitepaper_ShimCacheParser.pdf[Leveraging the Application Compatibility Cache in Forensic Investigations], by Andrew Davis, 2012

