*TODO add information about non-NT Registry versions*

:toc:
:toclevels: 4

== Session Manager

*TODO add some description*

The session manager settings are stored in the key:

....
CurrentControlSet\Control\Session Manager
....

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| BootExecute | REG_BINARY, REG_MULTI_SZ | The applications, services, and commands executed during start-up.
|===

== Language and codepage

=== Codepage

The codepage settings are stored in the key:

....
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage
....

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| # | REG_SZ | The code page file name +
Where # is the code page number, e.g. 1252 +
Contains a string with the name of the corresponding file e.g. c_1252.nls
| ACP | REG_SZ | The default ANSI (extended ASCII) code page +
Contains a string with the number of the corresponding code page e.g. 1252
| MACCP | REG_SZ | The default Macintosh code page +
Contains a string with the number of the corresponding code page e.g. 1252
| OEMCP | REG_SZ | The default OEM code page +
Contains a string with the number of the corresponding code page e.g. 1252
| OEMHAL | REG_SZ | [yellow-background]*Unknown* +
Contains a string with the name of the corresponding file e.g. vgaoem.fon
|===

== Run and Run Once keys

Run and Run Once keys cause programs to run each time a user logs on. There a 
per-user and per-system Run and Run Once keys.

Per-user Run and Run Once keys

....
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunOnce
....

Per-system Run and Run Once keys

....
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce
....

Only on Windows 95, 98, Me.

Run in the background when the logon dialog box first appears, or at the boot 
process stage if there is no logon.

....
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunServices
....
....
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce
....

Contains first-boot activities after setup or when the Add/Remove Programs 
Wizard was used.

....
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce\Setup
....

*TODO add description of sub keys and values*

....
description-string=commandline
....

According to http://msdn.microsoft.com/en-us/library/aa376977(v=vs.85).aspx[MSDN]:
[quote]
____
By default, the value of a RunOnce key is deleted before the command line is 
run. You can prefix a RunOnce value name with an exclamation point (!) to defer 
deletion of the value until after the command runs. Without the exclamation 
point prefix, if the RunOnce operation fails the associated program will not be 
asked to run the next time you start the computer.

By default, these keys are ignored when the computer is started in Safe Mode. 
The value name of RunOnce keys can be prefixed with an asterisk (*) to force 
the program to run even in Safe mode.
____

*TODO what about*

....
HKLM\Software\Microsoft\Windows\CurrentVersion\policies\Explorer\Run
HKCU\Software\Microsoft\Windows NT\CurrentVersion\Windows\Run
....

== Notes

Installed "Programs and Features"

....
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer
....

=== USBSTOR

....
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Enum\USBSTOR
....

Sub key level 1: Disk&Ven_&Prod_&Rev_0.00
....
<Device Type>&Ven_<Vendor>&Prod_<Product>&Rev_<Revision Number>
....

Sub key level 2: 1002131402536a&0

*Sub keys:*

* Device Parameters
* LogConf
* Properties

*Values:*

* Capabilities
* Class
* ClassGUID
* CompatibleIDs
* ConfigFlags
* ContainerID
* DeviceDesc
* Driver
* FriendlyName
* HardwareID
* Mfg
* Service

=== System restore

....
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\SystemRestore
....

=== Windows system locations

....
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion
....

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| CommonFilesDir | REG_SZ |
| DevicePath | REG_SZ |
| MediaPath | REG_SZ |
| MediaPathUnexpanded | REG_SZ |
| PF_AccessoriesName | |
| ProductId | |
| ProgramFilesDir | REG_SZ |
| SM_AccessoriesName | |
| SM_ConfigureProgramsExisted | |
| SM_ConfigureProgramsName | |
| SM_GamesName | |
| WallPaperDir | REG_SZ |
|===

=== Windows version information

....
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion
....

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| BuildLab | REG_SZ |
| CSDVersion | REG_SZ | Service pack
| CurrentBuild | REG_SZ | Current build (obsolete) e.g. 1.511.1
| CurrentBuildNumber | REG_SZ | Current build number e.g. 2600
| CurrentType | REG_SZ |
| CurrentVersion | REG_SZ | Current major and minor version e.g. 5.1
| DigitalProductId | REG_BINARY |
| InstallDate | REG_LONG |
| LicenseInfo | REG_BINARY |
| PathName | REG_SZ | Windows path name e.g. C:\Windows
| ProductId | REG_SZ | Product identifier
| ProductName | REG_SZ | Product name e.g Microsoft Windows XP
| RegDone | |
| RegisteredOrganization | REG_SZ | Registered organization
| RegisteredOwner | REG_SZ | Registered owner
| SoftwareType | REG_SZ | Software type e.g. SYSTEM
| SourcePath | REG_SZ |
| SubVersionNumber | |
| SystemRoot | REG_SZ | The system root also the value of %SystemRoot%
|===

== Also see

* https://github.com/libyal/winreg-kb/wiki/Time-zone-keys[Time Zone Keys]

== External Links

* http://technet.microsoft.com/en-us/library/cc963230.aspx[MSDN: BootExecute]
* http://msdn.microsoft.com/en-us/library/aa376977(v=vs.85).aspx[MSDN: Run and RunOnce Registry Keys]

