*TODO some random notes for now*

:toc:
:toclevels: 4

== Folder Redirection Keys
Folders that can be redirected:

* Application Data
* Desktop
* My Documents folder
* My Pictures folder
* Start menu

....
HKEY_CURRENT_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
HKEY_CURRENT_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
....

....
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
....

== MUI Cache
*TODO*

....
HKEY_CURRENT_USER\Software\Microsoft\Windows\ShellNoRoam\MUICache
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache
....

== Typed Paths
*TODO*

....
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths
....

[options="header"]
|===
| Value| Data type| Description
| %ITEM% | REG_SZ | Where %ITEM% is a string in the form: "url[0-9]+"
|===

== Notes

....
HKEY_CURRENT_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\BitBucket\%VOLUME_LETTER%\VolumeSerialNumber
....

== External Links

* http://support.microsoft.com/kb/242557[kb242557: Registry Settings for Folder Redirection in Windows]
* https://msdn.microsoft.com/en-us/library/windows/desktop/cc144093(v=vs.85).aspx[MSDN: Implementing the Basic Folder Object Interfaces]

