*TODO some random notes for now*

:toc:
:toc-placement: manual
:toc-title: 
:toclevels: 4

[preface]
== Table of contents
toc::[]

== Known folder identifier keys
Introduced in Windows Vista.

....
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions
....

Values:

[options="header"]
|===
| Value | Data type | Description
| Name | |
| LocalizedName | |
|===

== Shell Folder CLSID sub key
The shell folder CLSID sub key can be found in some https://github.com/libyal/winreg-kb/wiki/Component-Object-Model-keys[COM Class Identifier (CLSID) keys].

....
HKEY_CLASSES_ROOT\CLSID\{%GUID%}\ShellFolder
....

Sub keys specific to folder identifiers:

[options="header"]
|===
| Name | Description
| shell |
| shellex |
| ShellFolder |
|===

Values:

[options="header"]
|===
| Value | Data type | Description
| (default value) | |
| InfoTip | |
| LocalizedString | |
| SortOrderIndex | |
|===

=== Shell Folder sub key
Values:

[options="header"]
|===
| Value | Data type | Description
| Attributes | REG_DWORD |
| CallForAttributes | |
| HideOnDesktopPerUser | |
|===

=== Attributes values

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000010 | SFGAO_CANRENAME | The extension's root folder can be renamed by the user. The folder's shortcut menu will have a Rename item.
| 0x00000020 | SFGAO_CANDELETE | The extension's root folder can be deleted by the user. The folder's shortcut menu will have a Delete item.
| 0x00000040 | SFGAO_HASPROPSHEET | The extension's root folder has a Properties property sheet. The folder's shortcut menu will have a Properties item.
| | |
| 0x20000000 | SFGAO_FOLDER | The extension's root folder contains one or more items.
| 0x80000000 | SFGAO_HASSUBFOLDER | The extension's root folder contains one or more subfolders. Windows Explorer will place a plus sign ( `+` ) next to the folder icon.
|===

=== Localized String value data
The Localize String value contains a localized version of the folder name, e.g. on Windows XP the folder identifier key:

....
HKEY_CLASSES_ROOT\CLSID\{450d8fba-ad25-11d0-98a8-0800361b1103}
....

Has a LocalizedString value with the following data:

....
@%SystemRoot%\system32\SHELL32.dll,-9227
....

Which is the https://github.com/libyal/winreg-kb/wiki/MUI-form[MUI Form] for "My Documents".

== Folder Redirection Keys
Folders that can be redirected:

* Application Data
* Desktop
* My Documents folder
* My Pictures folder
* Start menu

....
HKEY_CURRENT_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
HKEY_CURRENT_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
....

....
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders
....

== MUI Cache
*TODO*

....
HKEY_CURRENT_USER\Software\Microsoft\Windows\ShellNoRoam\MUICache
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache
....

== Typed Paths
*TODO*

....
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths
....

[options="header"]
|===
| Value| Data type| Description
| %ITEM% | REG_SZ | Where %ITEM% is a string in the form: "url[0-9]+"
|===

== Notes

....
HKEY_CURRENT_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\BitBucket\%VOLUME_LETTER%\VolumeSerialNumber
....

== External Links

* http://support.microsoft.com/kb/242557[kb242557: Registry Settings for Folder Redirection in Windows]
* https://msdn.microsoft.com/en-us/library/windows/desktop/cc144093(v=vs.85).aspx[MSDN: Implementing the Basic Folder Object Interfaces]

